server:
  port: 8081
  servlet:
    context-path: /hah

dubbo:
  application:
    name: demo
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
    protocol: zookeeper
  scan:
    base-packages: com.example.demo.dubbo.service
  consumer:
    check: false


