server:
  port: 8082

dubbo:
  application:
    name: demo
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.example.demo.dubbo.service
